add:
  # Group B:
  # type={add_Kq, inv_sqrt}, N={16,32,64}, q={97,257,433}, train={100K,1M}, test=10K
  q_list: [97, 257, 433]
  N_list: [16, 32, 64]
  qN_pairs: []

  sample_size_pairs:
    - train: 100000
      test: 10000
    - train: 1000000
      test: 10000

  dataset_types:
    - add_Kq
    - inv_sqrt
    - default

  gpu_ids: null
  save_dir_template: "data/N{N}_q{q}/{type}"
  random_seed: 42
  backend: "multiprocessing"
  n_jobs: -1
